[package]
name = "esp32_hardware_interface"
version = "0.1.0"
authors = ["TristanG11 <tristanogandagaguerick@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "esp32_hardware_interface"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"
incremental = false

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
incremental = true

[features]
default = []

#experimental = ["esp-idf-svc/experimental"]

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
embedded-hal = "1.0.0-rc.1"
esp-idf-hal = "0.45"
esp-idf-sys = "0.36.0"
parking_lot = "0.12.3"
[build-dependencies]
embuild = { version = "0.32.0", features = ["espidf"] }
cc = "=1.1.30" # Version "1.1.30" necessary until a new version of `esp-idf-sys` is released