[package]
name = "serial_port_watcher_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rclrs = "0.4.1"
serialport = "4.6.1"
msg_utils ={path = "../../../../install/msg_utils/share/msg_utils/rust/" }
diagnostic_msgs = "*"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"

[[bin]]
name = "serial_port_watcher_rs"
path = "src/main.rs"

[package.metadata.ros]
install_to_share = ["config"]
