std_msgs/Header header         # Métadonnées pour l'horodatage et l'ID de la frame
float64 battery_voltage        # Tension principale de la batterie (en volts)
float64 front_right_motor      # Tension du moteur avant droit (en volts)
float64 front_left_motor       # Tension du moteur avant gauche (en volts)
float64 rear_left_motor        # Tension du moteur arrière gauche (en volts)
float64 rear_right_motor       # Tension du moteur arrière droit (en volts)
