name: ROS2 CI Workflow

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-colcon-common-extensions -y
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build packages
        run: |
          colcon build --event-handlers console_direct+

      - name: Run tests
        run: |
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
