name: GTest CI

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev

      - name: Build Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo mv libg* /usr/lib/

      - name: Build and run test for nmea_gnss_cpp
        run: |
          cd src/nmea_gnss_cpp
          mkdir -p build
          cd build
          cmake ..
          make
          ctest --output-on-failure
