name: ROS2 CI

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.3
        with:
          distribution: humble

      - name: Uninstall conflicting package
        run: |
          sudo pip uninstall -y em

      - name: Install empy package
        run: |
          pip install empy

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-common-extensions

      - name: Verify installed packages
        run: pip list | grep -E 'em|empy'

      - name: Install ROS 2 dependencies
        run: |
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
      
      - name: Clean workspace
        run: |
          rm -rf build install log

      - name: Verify installed packages again
        run: pip list | grep -E 'em|empy'
        
      - name: Build the workspace
        run: |
          colcon build 

      - name: Run tests
        run: |
          colcon test --event-handlers console_cohesion+
          colcon test-result
