name: ROS2 CI Build

on:
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: humble  

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install --upgrade empy
        pip install --upgrade colcon-common-extensions colcon-core

    - name: Install ROS dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions ros-humble-ament-cmake

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --continue-on-error

    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon test --event-handlers console_cohesion+

    - name: Test result summary
      run: |
        source /opt/ros/humble/setup.bash
        colcon test-result --verbose
