name: ROS2 CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.2
        with:
          distro: humble

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-colcon-common-extensions -y
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build packages
        run: |
          colcon build --event-handlers console_direct+

      - name: Run tests
        run: |
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
