name: CI

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  noop:
    runs-on: ubuntu-22.04
    if: false  # Cette condition empêche l'exécution du job
    steps:
      - name: This job will never run
        run: echo "This job is intentionally skipped."
