name: CI

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev

    - name: Build and Run Tests for nmea_gnss_cpp
      run: |
        cd src/nmea_gnss_cpp
        cmake -S . -B build
        cmake --build build
        cd build
        ctest --output-on-failure
