name: ROS2 CI Build

on:
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: humble  

    - name: Install Python dependencies
      run: |
        sudo apt-get update
        pip uninstall -y em
        sudo apt-get install -y python3-colcon-common-extensions ros-humble-ament-cmake python3-empy

    - name: Install Gazebo and ROS Gazebo Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ros-humble-gazebo-ros-pkgs

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --continue-on-error

    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon test --event-handlers console_cohesion+

    - name: Test result summary
      run: |
        source /opt/ros/humble/setup.bash
        colcon test-result --verbose
